name: CI

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang clang-tidy clang-format make g++

      - name: Run clang-format
        run: |
          find src include -name '*.cpp' -o -name '*.h' | xargs clang-format --dry-run --Werror

      - name: Run clang-tidy
        run: |
          clang-tidy src/*.cpp -- -Iinclude

      - name: Build
        run: |
          make
